version: 2.1
jobs:

  build_gcc_09:
    docker:
      - image: gcc:9
    steps:
      - checkout
      - run: c++ --version
      - run: mkdir build
      - run: cd build
      - run: cmake ..
      - run: make -j 2
      - run: ctest

  build_gcc_10:
    docker:
      - image: gcc:10
    steps:
      - checkout
      - run: c++ --version
      - run: mkdir build
      - run: cd build
      - run: cmake ..
      - run: make -j 2
      - run: ctest

  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: c++ --version
      - run: mkdir build
      - run: cd build
      - run: cmake ..
      - run: make -j 2
      - run: ctest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_09
      - build_gcc_10
      - build_gcc_latest
